schema_version = "1.0.0"

id = "Adapta_Nokto"
version = "1.1.2"
name = "Adapta Nokto"
tagline = "Adapta Nokto theme"
maintainer = "Cyrill Vitkovskiy"
type = "theme"
website = "https://github.com/Furash/blender_nokto"
tags = ["Dark"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]
